## 2.1 신경망과의 첫 만남
-흑백 손글씨 숫자 이미지(28 * 28 픽셀)를 10개의 범주(0~9)로 분류하기
- MNIST 데이터셋
    - 딥러닝계의 "Hello World"
    - 넘파이 배열 형태로 케라스에 이미 포함되어 있음

### 케라스에서 MNIST 데이터셋 적재하기

In [24]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

- 데이터 형태 확인

In [2]:
train_images.shape, len(train_labels)   # 3차원 배열로 되어 있고, 6만 장의 이미지 데이터가 존재합니다.

((60000, 28, 28), 60000)

In [3]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [25]:
test_images.shape, len(test_labels)     # 3차원 배열로 되어 있고, 1만 장의 이미지 데이터가 존재합니다.

((10000, 28, 28), 10000)

In [26]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

### 신경망 구조

In [27]:
from keras.api._v2.keras import activations
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation = "relu"),     # 입력
    layers.Dense(10, activation = "softmax")    # 출력. 10 : 예측할 범주의 갯수
])

### 컴파일 단계
- 옵티마이저(optimizer) : 성능을 향상시키기 위해 입력된 데이터를 기반으로 모델을 업데이트하는 메커니즘
- 손실 함수(loss function) : 훈련 데이터에서 모델의 성능을 측정하는 방법. 모델이 옳은 방향으로 학습될 수 있도록 도와줌
- 훈련과 테스트 과정을 모니터링할 지표 : 여기서는 정확도(정확히 분류된 이미지의 비율)만을 고려하겠음

In [28]:
model.compile(optimizer="rmsprop",
              loss = "sparse_categorical_crossentropy",
              metrics = ["accuracy"])

### 이미지 데이터 준비
- 데이터를 모델에 맞는 크기로 바꾸기
- 데이터타입 변경(연산할 때 데이터타입 미매칭으로 인한 오류가 생김)
    - 0과 1사이의 값을 가지는 "float32" 타입으로 변경
- 신경망은 입력 데이터의 스케일에 민감하여 적절한 데이터 전처리 과정이 필요합니다.
    - 이미지의 경우 보통 픽셀의 최댓값인 255로 나누어 사용합니다.

In [29]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
train_images = train_images.astype("float32") / 255

### 모델 훈련하기
- fit()

In [30]:
model.fit(train_images, train_labels, epochs=5, batch_size = 128)

Epoch 1/5
469/469 [==============================] - 2s 3ms/step - loss: 2.2323 - accuracy: 0.2461
Epoch 2/5
469/469 [==============================] - 1s 3ms/step - loss: 1.6496 - accuracy: 0.6001
Epoch 3/5
469/469 [==============================] - 1s 3ms/step - loss: 1.0257 - accuracy: 0.7511
Epoch 4/5
469/469 [==============================] - 1s 3ms/step - loss: 0.7377 - accuracy: 0.8110
Epoch 5/5
469/469 [==============================] - 2s 4ms/step - loss: 0.5982 - accuracy: 0.8403


### 모델을 사용하여 예측 만들기

In [32]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 18ms/step


array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [33]:
predictions[0].argmax()

7

In [34]:
predictions[0][7]

1.0

In [35]:
test_labels[0]

7

### 새로운 데이터에서 모델 평가하기

In [36]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print("테스트 정확도", test_acc)

313/313 [==============================] - 1s 3ms/step - loss: 13098.5332 - accuracy: 0.7224
테스트 정확도 0.7224000096321106
